// <auto-generated />
using System;
using BlackoutGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlackoutGuard.Infrastructure.Migrations
{
    [DbContext(typeof(BlackoutGuardDbContext))]
    [Migration("20260820195922_AddTimezoneIdToFacilities")]
    partial class AddTimezoneIdToFacilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.AlarmRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedBy");

                    b.HasIndex("FacilityId", "State")
                        .HasDatabaseName("idx_alarms_facility_state");

                    b.ToTable("alarm_records", null, t =>
                        {
                            t.HasCheckConstraint("CK_alarm_records_severity", "severity IN ('Info','Warning','Critical')");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.DecisionAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AffectedLoadId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("TriggeringFrequency")
                        .HasColumnType("double precision");

                    b.Property<double?>("TriggeringVoltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AffectedLoadId");

                    b.HasIndex("FacilityId", "TimestampUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_facility_time");

                    b.ToTable("decision_audit_log", (string)null);
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("GeneratorCapacityKW")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_facilities_tenant");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Load", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("CriticalityQ1")
                        .HasColumnType("smallint");

                    b.Property<short?>("CriticalityQ2")
                        .HasColumnType("smallint");

                    b.Property<short?>("CriticalityQ3")
                        .HasColumnType("smallint");

                    b.Property<short?>("CriticalityQ4")
                        .HasColumnType("smallint");

                    b.Property<double?>("CriticalityScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSheddable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("PowerRatingKw")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("PriorityMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("auto");

                    b.Property<int>("RelayAddress")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("idx_loads_facility");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_loads_zone");

                    b.HasIndex("FacilityId", "Priority")
                        .HasDatabaseName("idx_loads_priority")
                        .HasFilter("is_active = true");

                    b.HasIndex("FacilityId", "RelayAddress")
                        .IsUnique()
                        .HasDatabaseName("uq_relay_per_facility");

                    b.ToTable("loads", null, t =>
                        {
                            t.HasCheckConstraint("CK_loads_criticality_q1", "criticality_q1 BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_loads_criticality_q2", "criticality_q2 BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_loads_criticality_q3", "criticality_q3 BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_loads_criticality_q4", "criticality_q4 BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_loads_power_rating_kw", "power_rating_kw >= 0");

                            t.HasCheckConstraint("CK_loads_priority", "priority IN ('P1','P2','P3')");

                            t.HasCheckConstraint("CK_loads_priority_mode", "priority_mode IN ('auto','manual')");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.LoadCooldownState", b =>
                {
                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRestoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastShedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LoadId");

                    b.ToTable("load_cooldown_state", (string)null);
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CooldownSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("idx_rules_facility");

                    b.ToTable("rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_rules_cooldown_seconds", "cooldown_seconds >= 0");

                            t.HasCheckConstraint("CK_rules_parameter_key", "parameter_key IN ('FREQ_LOW','FREQ_HIGH','VOLT_LOW','VOLT_HIGH','LOAD_SHED_TIMER')");

                            t.HasCheckConstraint("CK_rules_value_order", "min_value <= max_value");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("trial");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.TimeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<short[]>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TargetPriority")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("idx_schedules_facility");

                    b.HasIndex("LoadId")
                        .HasDatabaseName("idx_schedules_load");

                    b.ToTable("time_schedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_time_schedules_target_priority", "target_priority IN ('P1','P2','P3')");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_email_per_tenant");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "role IN ('Admin','Operator','Viewer')");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("idx_zones_facility");

                    b.HasIndex("ParentZoneId")
                        .HasDatabaseName("idx_zones_parent");

                    b.ToTable("zones", null, t =>
                        {
                            t.HasCheckConstraint("CK_zones_type", "type IN ('building','floor','room')");
                        });
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.AlarmRecord", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.User", "AcknowledgedByUser")
                        .WithMany("AcknowledgedAlarms")
                        .HasForeignKey("AcknowledgedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("AlarmRecords")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcknowledgedByUser");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.DecisionAuditLog", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Load", "AffectedLoad")
                        .WithMany("DecisionAuditLogs")
                        .HasForeignKey("AffectedLoadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("DecisionAuditLogs")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffectedLoad");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Facility", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Tenant", "Tenant")
                        .WithMany("Facilities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Load", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("Loads")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Zone", "Zone")
                        .WithMany("Loads")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.LoadCooldownState", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Load", "Load")
                        .WithOne("LoadCooldownState")
                        .HasForeignKey("BlackoutGuard.Infrastructure.Persistence.Models.LoadCooldownState", "LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Rule", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("Rules")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.TimeSchedule", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("TimeSchedules")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Load", "Load")
                        .WithMany("TimeSchedules")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.User", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Zone", b =>
                {
                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Facility", "Facility")
                        .WithMany("Zones")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackoutGuard.Infrastructure.Persistence.Models.Zone", "ParentZone")
                        .WithMany("ChildZones")
                        .HasForeignKey("ParentZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Facility");

                    b.Navigation("ParentZone");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Facility", b =>
                {
                    b.Navigation("AlarmRecords");

                    b.Navigation("DecisionAuditLogs");

                    b.Navigation("Loads");

                    b.Navigation("Rules");

                    b.Navigation("TimeSchedules");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Load", b =>
                {
                    b.Navigation("DecisionAuditLogs");

                    b.Navigation("LoadCooldownState");

                    b.Navigation("TimeSchedules");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Tenant", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.User", b =>
                {
                    b.Navigation("AcknowledgedAlarms");
                });

            modelBuilder.Entity("BlackoutGuard.Infrastructure.Persistence.Models.Zone", b =>
                {
                    b.Navigation("ChildZones");

                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
